import React, { useState } from 'react';

import { Checkbox } from '@components';
import { Sidebar, Header } from '../components';

import { getClassName } from '@helpers';

import './styles.scss';

const UsersScreen = () => {
  const [menuOpen, setMenuOpen] = useState(false);

  const toggleMenu = () => {
    setMenuOpen(!menuOpen);
  };

  return (
    <div className={getClassName('users-box', menuOpen && 'menu-open')}>
      <Sidebar />

      <div className='users-content'>
        <Header title={'Template Name'} isMenu={menuOpen} toggleMenu={toggleMenu} />

        <div className='users-container'>
          <table className='data-table'>
            <thead>
              <tr>
                <th>One</th>
                <th>Two</th>
                <th>Three</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>
                  <Checkbox
                    label={'name'}
                    onClick={(event) => {
                      console.log('onClick', event, event.target, event.target.value);
                    }}
                    disabled={true}
                    checked={true}
                    containerClassName={'test-container'}
                    labelClassName={'test-label'}
                    checkboxClassName={'test-checkbox'}
                  />
                </td>
                <td>1</td>
                <td>2</td>
              </tr>
              <tr>
                <td>
                  <Checkbox disabled={true} label={'asdasdasd'} />
                </td>
                <td>4</td>
                <td>5</td>
              </tr>
              <tr>
                <td>
                  <Checkbox />
                </td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
              <tr>
                <td>dgdfg</td>
                <td>dfgdfg</td>
                <td>dfgdfg</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

export default UsersScreen;
